// src/constants/categories.ts

export const mainCategories = [
     "all",
     "politics",
     "sports",
     "crypto",
     "finance",
     "geopolitics",
     "earnings",
     "tech",
     "culture",
     "world",
     "economy",
     "climate-science",
     "elections",
   ] as const;
   
   export const categoryLabels: Record<string, string> = {
     all: "All",
     politics: "Politics",
     sports: "Sports",
     crypto: "Crypto",
     finance: "Finance",
     geopolitics: "Geopolitics",
     earnings: "Earnings",
     tech: "Tech",
     culture: "Culture",
     world: "World",
     economy: "Economy",
     "climate-science": "Climate & Science",
     elections: "Elections",
   };
   
   export const categoryKeywords: Record<string, string[]> = {
     politics: [
       "trump",
       "biden",
       "kamala",
       "harris",
       "election",
       "vote",
       "congress",
       "senate",
       "president",
       "democrat",
       "republican",
       "politics",
     ],
     elections: ["election", "vote", "president", "primary", "ballot", "campaign"],
     crypto: [
       "bitcoin",
       "btc",
       "eth",
       "ethereum",
       "solana",
       "crypto",
       "token",
       "blockchain",
       "nft",
       "defi",
     ],
     finance: ["stock", "fed", "interest rate", "inflation", "bond", "treasury", "finance"],
     sports: [
       "nfl",
       "nba",
       "super bowl",
       "ncaa",
       "world cup",
       "olympics",
       "football",
       "basketball",
       "baseball",
       "sports",
     ],
     geopolitics: [
       "war",
       "ukraine",
       "russia",
       "china",
       "taiwan",
       "iran",
       "israel",
       "palestine",
       "regime",
       "military",
     ],
     culture: [
       "oscar",
       "grammy",
       "movie",
       "tv",
       "music",
       "celebrity",
       "hollywood",
       "gta",
       "game",
       "album",
       "music",
     ],
     tech: ["apple", "google", "ai", "openai", "tesla", "elon", "meta", "x.com", "tech"],
     economy: ["gdp", "recession", "jobs", "unemployment", "tariff", "economy"],
     world: ["world", "global", "international", "eu", "nato"],
     "climate-science": ["climate", "temperature", "co2", "nasa", "space", "vaccine", "science"],
   };